AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    e261f7d4-8c04-4c51-bb9f-9f0def3ba233:
      size:
        width: 60
        height: 60
      position:
        x: 403
        'y': 157
      z: 0
    48d2f62d-ec35-4808-8cba-f7d7282258ab:
      size:
        width: 60
        height: 60
      position:
        x: 236
        'y': 151
      z: 0

Parameters:

  LambdaName:
    Description: "Name for this function"
    Type: "String"
    
Resources:
  demofunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref LambdaName
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            message = 'Hello Lambda World!'
            return message
      Role: 'arn:aws:iam::148034182407:role/dboperationsrole'
      Runtime: python3.9
      Environment:
        Variables:
          TableName: !Ref demotable
      Timeout: 120
    DependsOn:
      - demotable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e261f7d4-8c04-4c51-bb9f-9f0def3ba233 
  demotable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: myfirstdemotable
      AttributeDefinitions:
        - AttributeName: "student_name"
          AttributeType: "S"
        - AttributeName: "subject_title"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "student_name"
          KeyType: "HASH"
        - AttributeName: "subject_title"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 48d2f62d-ec35-4808-8cba-f7d7282258ab
  demofunctionnew:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: mynewdemofunction
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            message = 'Hello Lambda World!'
            return message
      Role: 'arn:aws:iam::148034182407:role/dboperationsrole'
      Runtime: python3.9
      Timeout: 120
      Layers:
        - !Ref libs
    DependsOn:
      - newdemotable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e261f7d4-8c04-4c51-bb9f-9f0def3ba233
  newdemotable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: mynewfirstdemotable
      AttributeDefinitions:
        - AttributeName: "book_title"
          AttributeType: "S"
        - AttributeName: "book_author"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "book_title"
          KeyType: "HASH"
        - AttributeName: "book_author"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 48d2f62d-ec35-4808-8cba-f7d7282258ab
  libs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: python-requests-lib
      Description: Dependencies for requests lib module for python.
      Content:
        S3Bucket: lambdalayernew
        S3Key: python.zip
      CompatibleRuntimes:
        - python3.9  