
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
    
Resources:
  demofunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mydemofunction
      Handler: index.lambda_handler
      CodeUri: ./index.py
      Role: 'arn:aws:iam::148034182407:role/dboperationsrole'
      Runtime: python3.9
      Timeout: 120